[package]
name = "cbor_next"
version = "0.1.0"
edition = "2024"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/sqlx_migrator"
repository = "https://github.com/iamsauravsharma/sqlx_migrator"
description = "CBOR encoder and decoder"
license = "MIT"
readme = "README.MD"
keywords = ["cbor"]

[dependencies]
thiserror = "2.0.12"

[dev-dependencies]
hex = "0.4.3"
